In [31]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1., 2.], [ 2., 0., 0.], [ 0., 1., -1.]])
scaler = preprocessing.StandardScaler().fit(X_train)
vector_unnorm = np.array([[0.3, 0.5, 3]])
scaler.transform(vector_unnorm)

array([[-0.85732141,  0.61237244,  2.13808994]])

In [32]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
scaler.fit(data)
print(scaler.data_max_)
print(scaler.transform(data))

[ 1. 18.]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [33]:
enc = preprocessing.OrdinalEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)
enc.transform([['female', 'from US', 'uses Safari']])


array([[0., 1., 1.]])

In [34]:
enc = preprocessing.OneHotEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)
enc.transform([['female', 'from US', 'uses Safari'],
 ['male', 'from Europe', 'uses Safari']]).toarray()

array([[1., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 1.]])

In [39]:
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')
X = [[0, 1, 2],
         [3, 4, 5]]
dist.pairwise(X)
array([[ 0.        ,  5.19615242],
       [ 5.19615242,  0.        ]])

ImportError: cannot import name 'DistanceMetric' from 'sklearn.metrics' (C:\Users\nada7\anaconda3\lib\site-packages\sklearn\metrics\__init__.py)

In [45]:
import sklearn.metrics.DistanceMetric as skD
dist = skD.get_metric('euclidean')
X= [[0,1,2],[3,4,5]]
print(dist.pairwise(X))

ModuleNotFoundError: No module named 'sklearn.metrics.DistanceMetric'