In [15]:
from sklearn.neighbors import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')
X= [[0,1,2],[3,4,5]]
print(dist.pairwise(X))


[[0.         5.19615242]
 [5.19615242 0.        ]]


In [19]:

import numpy as np
X = [[1, 2, 2], [ -1,7, 5]]
print(X)
V=np.cov(X)
V

[[1, 2, 2], [-1, 7, 5]]


array([[ 0.33333333,  2.33333333],
       [ 2.33333333, 17.33333333]])

In [20]:
dist = DistanceMetric.get_metric('mahalanobis', V=np.cov(X))
print(dist.pairwise(V))

[[0.         3.60555128]
 [3.60555128 0.        ]]


In [45]:
import numpy as np
from sklearn.datasets import load_diabetes
X_diabetes, y_diabetes = load_diabetes(return_X_y=True)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_diabetes)
print(scaler.data_max_)
print(scaler.transform(X_diabetes))

[0.11072668 0.05068012 0.17055523 0.13204422 0.15391371 0.19878799
 0.18117906 0.18523444 0.13359898 0.13561183]
[[0.66666667 1.         0.58264463 ... 0.28208745 0.56221737 0.43939394]
 [0.48333333 0.         0.14876033 ... 0.14104372 0.22244301 0.16666667]
 [0.88333333 1.         0.51652893 ... 0.28208745 0.49658437 0.40909091]
 ...
 [0.68333333 1.         0.28512397 ... 0.24964739 0.30504048 0.56060606]
 [0.28333333 0.         0.49586777 ... 0.39351199 0.65702021 0.40909091]
 [0.28333333 0.         0.0661157  ... 0.14104372 0.46930778 0.51515152]]


In [61]:
V =np.cov(X_diabetes)
 

print(V)

[[ 1.53598255e-03 -7.25552524e-04  1.48716462e-03 ...  6.35182232e-04
  -3.14142357e-05 -2.50356714e-03]
 [-7.25552524e-04  2.03794840e-03 -2.89524546e-04 ... -1.92692294e-04
  -4.75328228e-04  2.36049599e-03]
 [ 1.48716462e-03 -2.89524546e-04  1.85540979e-03 ...  8.76732397e-04
  -4.45902447e-04 -2.14543937e-03]
 ...
 [ 6.35182232e-04 -1.92692294e-04  8.76732397e-04 ...  1.06321888e-03
  -8.50154998e-04 -1.28636380e-03]
 [-3.14142357e-05 -4.75328228e-04 -4.45902447e-04 ... -8.50154998e-04
   1.14114351e-03 -3.77758669e-04]
 [-2.50356714e-03  2.36049599e-03 -2.14543937e-03 ... -1.28636380e-03
  -3.77758669e-04  6.17853798e-03]]


In [63]:

dist = DistanceMetric.get_metric('mahalanobis', V=np.cov(X_diabetes))
print(dist.pairwise(vX))

[[0.                nan        nan ... 0.28467485 0.4050526  1.47533454]
 [       nan 0.         0.52998314 ... 0.26844771        nan 0.61861113]
 [       nan 0.52998314 0.         ... 0.29397911 0.47851118 1.2306047 ]
 ...
 [0.28467485 0.26844771 0.29397911 ... 0.         0.21292985 0.91298776]
 [0.4050526         nan 0.47851118 ... 0.21292985 0.         0.38597393]
 [1.47533454 0.61861113 1.2306047  ... 0.91298776 0.38597393 0.        ]]
