In [2]:
# Use the iris dataset as an example
import numpy as np # for numpy
# Now import a multiclassification model from a neural network for training multiclassification data
from sklearn.neural_network import MLPClassifier
# Now import the libraries in sklearn that are used to evaluate the prediction metrics, such as confusion matrices
#and classification reports
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris_data = load_iris()
X = iris_data.data
y = iris_data.target
X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.3, random_state=0)

In [3]:
# """
# Main parameters.
# hidden_layer_sizes: number of hidden layer cells (tuples), e.g. (100,100,100,50)
# activation : activation function, {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'; [f(x) = x, 1/(1+exp(-x)), tanh(x),
#max(0, x)]
# solver : solver, {'lbfgs', 'sgd', 'adam'}, default 'adam '; [newton method, stochastic gradient descent, adaptive
#momemtum]
# alpha : L2 regularization parameter, float, optional, default 0.0001
# batch_size : batch size, optional, not applicable to 'lbfgs', default 'auto', in this case, batch_size=min(200,
#n_samples)`
# learning_rate : learning rate, {'constant', 'invscaling', 'adaptive'}, default 'constant', only for gradient descent sgd
# learning_rate_init : initial value of the learning rate, optional, default 0.001, only for sgd or adam
# power_t : descent exponent, optional, default 0.5, applies to 'invscaling',learning_rate_init/pow(t,power_t), sgd only
# max_iter : maximum number of iterations, optional, default 200, number of iterator convergence iterations, for
#sgd/adam, represents the number of epochs, not the number of descent steps
# shuffle : per iteration, whether to shuffle or not, optional, default True, only for sgd or adam
# random_state: default None; if int, random number generator seed, if RandomStates instance, random number
#generator, if None, np.random
# tol : tolerance, optional, default le-4, stop iterating if loss does not reach this value in two consecutive iterations
#unless set to 'adaptive', otherwise
# beta_1 : adam exponent decay parameter 1, optional, default 0.9
# beta_2 : adam exponential decay parameter 2, optional, default 0.999
# epsilon : adam numerical stability value, optional, default 1e-8
# """

SyntaxError: unmatched ']' (Temp/ipykernel_19236/3044027182.py, line 5)

In [5]:
mlp = MLPClassifier(hidden_layer_sizes=(20),alpha=0.01,max_iter=300)
# The model can be trained by calling the fit function. The general method of training by calling the model function is
#fit()
mlp.fit(X_train,y_train) # Here the y value needs to be reduced to a one-dimensional array
# This is how the model is trained, and we can then call a variety of functions to get the trained parameters
# For example, to get the accuracy rate
print('The accuracy of the test set is:',mlp.score(X_test,y_test))
# e.g. output the current Current value of the loss function
print('The Current value of the loss function of the training set is:',mlp.loss_)
# For example, output the weights of each theta
print('The weight value :',mlp.coefs_)

The accuracy of the test set is: 0.7555555555555555
The Current value of the loss function of the training set is: 0.47502840629835674
The weight value : [array([[ 2.29361868e-01, -1.84662371e-01, -1.07750640e-01,
         1.88256473e-01, -2.20843874e-01, -2.04274842e-02,
         2.44952213e-01,  3.74655225e-01, -1.22549319e-01,
         2.63707251e-01,  2.69761436e-01,  2.86764247e-01,
         4.05970873e-01, -6.54786763e-02,  4.57786227e-01,
        -6.09816887e-03, -9.93848332e-02, -1.49940540e-01,
         3.41474617e-01, -1.78409938e-01],
       [ 2.18532255e-01, -2.41621981e-01, -1.07581323e-04,
        -1.46304799e-01, -4.21643294e-02,  4.48342920e-01,
         1.85997034e-01,  1.66325349e-01, -8.86936382e-04,
         2.80366949e-01, -5.71272604e-02, -2.21243863e-01,
        -3.27146567e-01,  3.20024257e-01,  1.28703430e-01,
         1.85013537e-02,  2.25010083e-09,  6.18989550e-05,
         3.69692493e-02, -2.07493180e-03],
       [-4.90173129e-01, -1.29817190e-01,  7.578768

C:\Users\nada7\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


In [7]:
# The confusion matrix and classification report is an indicator of the predicted and true values
# The confusion matrix provides a visual indication of the number of correct and incorrect classifications, and the
#category to which the correct samples were incorrectly classified
matrix_test = confusion_matrix(y_test,mlp.predict(X_test))
print('The confusion matrix for the training set is:\n',matrix_test)
# There are multiple metrics in the classification report to evaluate how good the prediction is.
# '''
# TP: Prediction is 1 (Positive), actual is also 1 (Truth-prediction is correct)
# TN: predicted 0 (Negative), also 0 (Truth - predicted correctly)
# FP: predicted 1 (Positive), actually 0 (False - wrong prediction)
# FN: Prediction is 0 (Negative), actual is 1 (False-prediction is wrong)
# '''
report_test = classification_report(y_test,mlp.predict(X_test))
print(f'The classification report for the training set is: \n {report_test}')

The confusion matrix for the training set is:
 [[16  0  0]
 [ 0  7 11]
 [ 0  0 11]]
The classification report for the training set is: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.39      0.56        18
           2       0.50      1.00      0.67        11

    accuracy                           0.76        45
   macro avg       0.83      0.80      0.74        45
weighted avg       0.88      0.76      0.74        45

